# -*- mode: ruby -*-
# vi: set ft=ruby :

TERRAFORM_VERSION='0.11.3'

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.synced_folder "~/", "/host"

  config.vm.provision "shell", path: './provisioning/default_setting.sh'
  config.vm.provision "shell", path: './provisioning/terraform.sh', args: TERRAFORM_VERSION

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
	  v.cpus = 2
  end
end
