# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.provider "docker" do |d|
    # d.image="nginx:latest"
    d.build_dir="."
  end
end
