# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/6"

  config.vm.synced_folder "~/", "/host"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", path: './provisioning/default_setting.sh'
  config.vm.provision "shell", path: './provisioning/nginx.sh'

  config.vm.provider "virtualbox" do |v|
	v.memory = 2048
	v.cpus = 2
  end
end
