# -*- mode: ruby -*-
# vi: set ft=ruby :

JENKINS_VERSION='latest'

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.synced_folder "~/", "/host"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provision "shell", path: './provisioning/default_setting.sh'
  config.vm.provision "shell", path: './provisioning/jenkins.sh', args: JENKINS_VERSION

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
	  v.cpus = 2
  end
end
